name: Linter
on: 
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pylint
      run: pip install pylint
    
    - name: Run linker.py on main.py
      run: python3 linker.py
      continue-on-error: false
